language: php

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
      env:
        - CS_CHECK=true
        - TEST_COVERAGE=true
    - php: 7
    - php: hhvm
  allow_failures:
    - php: hhvm

before_install:
  - composer self-update

install:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer require --dev --no-update michaelmoussa/php-coverage-checker:^1.1.0 ; fi
  - travis_retry composer install --no-interaction --ignore-platform-reqs --prefer-source
  - composer info -i

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage && vendor/bin/php-coverage-checker clover.xml 100 ; else composer test ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs ; fi

notifications:
  email: true
